services:

    ctn.bootstrapiconsinserttag.listener.generatepage:
        class: ContaoThemesNet\BootstrapIconsInserttag\EventListener\GeneratePageListener
        arguments:
            - "%bootstrap_config%"

    ctn.bootstrapiconsinserttag.listener.replaceinserttags:
        class: ContaoThemesNet\BootstrapIconsInserttag\EventListener\ReplaceInsertTagsListener
        public: true
        arguments:
            - "@contao.framework"
            - "%bootstrap_config%"
