parameters:
    bootstrap_config:
        source:
              use_cdn: false
              css_source: 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css'
              js_source:  'https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js'
        use:
            icon_font: true
            svg: true
