services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]
    _defaults:
        public: true

    ctn.bootstrapiconsinserttag.listener.hooks:
        class: ContaoThemesNet\BootstrapIconsInserttag\EventListener\HookListener
        public: true
        arguments:
            - "@contao.framework"
            - "%bootstrap_config%"
